# ¿Cuál es la mejor tarifa?

Trabajas como analista para el operador de telecomunicaciones Megaline. La empresa ofrece a sus clientes dos tarifas de prepago, Surf y Ultimate. El departamento comercial quiere saber cuál de las tarifas genera más ingresos para poder ajustar el presupuesto de publicidad.

Vas a realizar un análisis preliminar de las tarifas basado en una selección de clientes relativamente pequeña. Tendrás los datos de 500 clientes de Megaline: quiénes son los clientes, de dónde son, qué tarifa usan, así como la cantidad de llamadas que hicieron y los mensajes de texto que enviaron en 2018. Tu trabajo es analizar el comportamiento de los clientes y determinar qué tarifa de prepago genera más ingresos.

## Plan inicial de trabajo

Para este proyecto, pretendo analizar los diferentes datasets proporcionados con el objetivo de determinar cuál de los planes que ofrece la compañía celular es el más rentable para la empresa,en términos de revenue pero también de margen y consumo.

Para esto tendré que hacer una limpieza de datos, preprocesarlos para prepararlos para el análisis, luego usar algunas líneas de código que me permitirán extraer información relevante para el análisis, como las medidas de tendencia central, los montos facturados a nivel individual y grupal para los distintos planes, cantidad de usuarios activos, tiempo promedio de duración en cada plan. Estas son estimaciones preliminares, puede que sea necesario hacer cálculos adicionales o, algunos de los mencionados, sean innecesarios. Todo dependerá de la evolución del análisis per se.

Al finalizar, el objetivo es entregar un informe ejecutivo que señale lo trabajado con cada data set, los métodos y funciones aplicados para obtener los resultados, recomendaciones de negocio y un análisis respecto a las hipótesis planteadas.

También incluiremos gráficas para facilitar la visualización de datos y que sea más sencillo de comprender los comportamientos de las poblaciones analizadas, así como los planes de celular y el comportamiento de consumo

## Inicialización

In [1]:
# Cargar todas las librerías
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

## Cargar datos

In [2]:
# Carga los archivos de datos en diferentes DataFrames
calls_df = pd.read_csv("megaline_calls.csv")

In [3]:
internet_df = pd.read_csv("megaline_internet.csv")

In [4]:
messages_df = pd.read_csv("megaline_messages.csv")

In [5]:
plans_df = pd.read_csv("megaline_plans.csv")

In [6]:
users_df = pd.read_csv("megaline_users.csv")

## Preparar los datos

Usaremos métodos de pandas para visualizar la información de los DataFrames que hemos creado, entender si hay valores duplicados, ausentes, errores de formato, etc

## Tarifas

In [7]:
# Imprime la información general/resumida sobre el DataFrame de las tarifas
plans_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   messages_included      2 non-null      int64
 1   mb_per_month_included  2 non-null      int64
 2   minutes_included       2 non-null      int64
 3   usd_monthly_pay        2 non-null      int64
 4   usd_per_gb             2 non-null      int64
 5   usd_per_message        2 non-null      float64
 6   usd_per_minute         2 non-null      float64
 7   plan_name              2 non-null      str
dtypes: float64(2), int64(5), str(1)
memory usage: 260.0 bytes

In [8]:
# Imprime una muestra de los datos para las tarifas

plans_df.head()

,messages_included,mb_per_month_included,minutes_included,usd_monthly_pay,usd_per_gb,usd_per_message,usd_per_minute,plan_name
0,50,15360,500,20,10,0.03,0.03,surf
1,1000,30720,3000,70,7,0.01,0.01,ultimate

Se observan un par de posibles mejoras a los tipos de datos, sobre todo para mantener la coherencia en los mismos, puesto que hay 4 columnas que se refieren a una tarifa por x unidad de medida, pero 2 de ellas son int (usd_monthly_pay & usd_per_gb) y 2 son float (usd_per_message & usd_per_message) podemos convertir ambas a float para estandarizar, sin embargo, al ser ambas de tipo numérico, no habría problema para futuros cálculos

## Corregir datos

[Corrige los problemas obvios con los datos basándote en las observaciones iniciales.]

In [9]:
# Usamos el método astype() para cambiar el tipo de datos de ambas columnas
plans_df["usd_monthly_pay"] = plans_df["usd_monthly_pay"].astype(float) 
plans_df["usd_per_gb"] = plans_df["usd_per_gb"].astype(float)
print(plans_df.info()) # imprimimos info() para corroborar cambio

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   messages_included      2 non-null      int64
 1   mb_per_month_included  2 non-null      int64
 2   minutes_included       2 non-null      int64
 3   usd_monthly_pay        2 non-null      float64
 4   usd_per_gb             2 non-null      float64
 5   usd_per_message        2 non-null      float64
 6   usd_per_minute         2 non-null      float64
 7   plan_name              2 non-null      str
dtypes: float64(4), int64(3), str(1)
memory usage: 260.0 bytes
None

## Enriquecer los datos

[Agrega factores adicionales a los datos si crees que pudieran ser útiles.]

In [10]:
# no considero que se deban agregar factores adicionales por ahora

## Usuarios/as

In [10]:
# Imprime la información general/resumida sobre el ßDataFrame de usuarios
print(users_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     500 non-null    int64
 1   first_name  500 non-null    str
 2   last_name   500 non-null    str
 3   age         500 non-null    int64
 4   city        500 non-null    str
 5   reg_date    500 non-null    str
 6   plan        500 non-null    str
 7   churn_date  34 non-null     str
dtypes: int64(2), str(6)
memory usage: 31.4 KB
None

In [11]:
# Imprime una muestra de datos para usuarios
print(users_df.head())

   user_id first_name  last_name  age                                   city  \
0     1000   Anamaria      Bauer   45  Atlanta-Sandy Springs-Roswell, GA MSA
1     1001     Mickey  Wilkerson   28        Seattle-Tacoma-Bellevue, WA MSA
2     1002     Carlee    Hoffman   36   Las Vegas-Henderson-Paradise, NV MSA
3     1003   Reynaldo    Jenkins   52                          Tulsa, OK MSA
4     1004    Leonila   Thompson   40        Seattle-Tacoma-Bellevue, WA MSA

     reg_date      plan churn_date
0  2018-12-24  ultimate        NaN
1  2018-08-13      surf        NaN
2  2018-10-21      surf        NaN
3  2018-01-28      surf        NaN
4  2018-05-23      surf        NaN

Para este DataFrame observamos valores nulos en la columna "churn_date". Un total de 466 y, además, evidenciamos que la columna es de tipo string pero debería ser DateTime. 

El hecho de que hayan 466 valores ausentes, en este caso, es una buena señal, habla de que, de esta muestra de 500 registros, solo 34 usuarios han cancelado su plan con la compañía, representando un 6,8% de la muestra total. No obstante, hay información muy  valiosa que extraer de acá para entender los motivos de cancelación, qué tipo de planes son más propensos a ello, tiempo promedio de duración, edad de los usuarios, etc. (Los valores ausentes de esta columna, se quedan como ausentes para no interferir en el cambio de tipo de datos de la columna)

Por otro lado, el mismo problema de tipo de dayos se extiende a reg_date, debemos cambiarlo a DateTime.

Las demás columnas no tienen problema

### Corregir los datos

Cambiamos los tipos de datos de las columnas con fecha a tipo DateTime mediante el método todatetime()

In [34]:
users_df["churn_date"] = pd.to_datetime(users_df["churn_date"], errors="coerce")
users_df["reg_date"] = pd.to_datetime(users_df["reg_date"], errors="coerce")
print(users_df.info()) # Imprimimos info para corroborar cambio

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     500 non-null    int64
 1   first_name  500 non-null    str
 2   last_name   500 non-null    str
 3   age         500 non-null    int64
 4   city        500 non-null    str
 5   reg_date    500 non-null    datetime64[us]
 6   plan        500 non-null    str
 7   churn_date  34 non-null     datetime64[us]
dtypes: datetime64[us](2), int64(2), str(4)
memory usage: 31.4 KB
None

### Enriquecer los datos

[Agrega factores adicionales a los datos si crees que pudieran ser útiles.]

In [14]:
# por ahora, considero que no se necesitan factores adicionales en los datos del DataFrame

## Llamadas

In [13]:
# Imprime la información general/resumida sobre el DataFrame de las llamadas
calls_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 137735 entries, 0 to 137734
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         137735 non-null  str
 1   user_id    137735 non-null  int64
 2   call_date  137735 non-null  str
 3   duration   137735 non-null  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 4.2 MB

In [14]:
# Imprime una muestra de datos para las llamadas
print(calls_df.head())

         id  user_id   call_date  duration
0   1000_93     1000  2018-12-27      8.52
1  1000_145     1000  2018-12-27     13.66
2  1000_247     1000  2018-12-27     14.48
3  1000_309     1000  2018-12-28      5.76
4  1000_380     1000  2018-12-30      4.22

El único ajuste posible observado es el tipo de datos de la columna call_date, lo cambiaremos a DateTime puesto que actualmente es str

### Corregir los datos

In [35]:
calls_df["call_date"] = pd.to_datetime(calls_df["call_date"], errors="coerce") # Convertimos
print(calls_df.info()) # imprimimos info para corroborar

<class 'pandas.DataFrame'>
RangeIndex: 137735 entries, 0 to 137734
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         137735 non-null  str
 1   user_id    137735 non-null  int64
 2   call_date  137735 non-null  datetime64[us]
 3   duration   137735 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(1), str(1)
memory usage: 4.2 MB
None

### Enriquecer los datos

[Agrega factores adicionales a los datos si crees que pudieran ser útiles.]

In [18]:
# No se identifican factores adicionales posibles a agregar a este DataFrame

## Mensajes

In [19]:
# Imprime la información general/resumida sobre el DataFrame de los mensajes
messages_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76051 entries, 0 to 76050
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            76051 non-null  str
 1   user_id       76051 non-null  int64
 2   message_date  76051 non-null  str
dtypes: int64(1), str(2)
memory usage: 1.7 MB

In [20]:
# Imprime una muestra de datos para los mensajes
messages_df.head()

         id  user_id message_date
0  1000_125     1000   2018-12-27
1  1000_160     1000   2018-12-31
2  1000_223     1000   2018-12-31
3  1000_251     1000   2018-12-27
4  1000_255     1000   2018-12-26

La columna messqage_date tiene un formato incorrecto, corregiremos el tipo de datos con el método de Pandas todatetime()

### Corregir los datos

[Corrige los problemas obvios con los datos basándote en las observaciones iniciales.]

In [37]:
messages_df["message_date"] = pd.to_datetime(messages_df["message_date"], errors="coerce")
print(messages_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 76051 entries, 0 to 76050
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            76051 non-null  str
 1   user_id       76051 non-null  int64
 2   message_date  76051 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 1.7 MB
None

### Enriquecer los datos

[Agrega factores adicionales a los datos si crees que pudieran ser útiles.]

In [22]:
# no se considera relevante añadir factores adicionales al DataFrame

## Internet

In [22]:
# Imprime la información general/resumida sobre el DataFrame de internet
internet_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 104825 entries, 0 to 104824
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            104825 non-null  str
 1   user_id       104825 non-null  int64
 2   session_date  104825 non-null  str
 3   mb_used       104825 non-null  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 3.2 MB

In [23]:
# Imprime una muestra de datos para el tráfico de internet
internet_df.head()

         id  user_id session_date  mb_used
0   1000_13     1000   2018-12-29    89.86
1  1000_204     1000   2018-12-31     0.00
2  1000_379     1000   2018-12-28   660.40
3  1000_413     1000   2018-12-26   270.99
4  1000_442     1000   2018-12-27   880.22

Se identifica la misma inconsistencia de los anteriores DataFrames respecto al tipo de datos de la columna con fecha

### Corregir los datos

[Corrige los problemas obvios con los datos basándote en las observaciones iniciales.]

In [38]:
internet_df["session_date"] = pd.to_datetime(internet_df["session_date"], errors="coerce")
print(internet_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 104825 entries, 0 to 104824
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            104825 non-null  str
 1   user_id       104825 non-null  int64
 2   session_date  104825 non-null  datetime64[us]
 3   mb_used       104825 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(1), str(1)
memory usage: 3.2 MB
None

### Enriquecer los datos

[Agrega factores adicionales a los datos si crees que pudieran ser útiles.]

In [26]:
# No es necesario agregar nada adicional al DataFrame por ahora

## Estudiar las condiciones de las tarifas

[Es sumamente importante entender cómo funcionan las tarifas, cómo se les cobra a los usuarios en función de su plan de suscripción. Así que te sugerimos imprimir la información de la tarifa para ver una vez más sus condiciones.]

In [25]:
# Imprime las condiciones de la tarifa y asegúrate de que te quedan claras
# Definimos las características de cada plan como variables para usarlas en futuros cálculos
surf_monthly_fee = 20
surf_minutes_included = 500
surf_sms_included = 50
surf_gb_included = 15
surf_minute_overage = 0.03
surf_sms_overage = 0.03
surf_gb_overage = 10

ultimate_monthly_fee = 70
ultimate_minutes_included = 3000
ultimate_sms_included = 1000
ultimate_gb_included = 30
ultimate_minute_overage = 0.01
ultimate_sms_overage = 0.01
ultimate_gb_overage = 7

In [26]:
# Imprimimos de manera organizada las características de cada plan
print("*** CONDICIONES DE LAS TARIFAS ***\n")

print("TARIFA SURF:")
print(f"- Pago mensual: ${surf_monthly_fee}")
print(f"- Minutos incluidos: {surf_minutes_included}")
print(f"- SMS incluidos: {surf_sms_included}")
print(f"- GB incluidos: {surf_gb_included}")
print(f"- Costo por minuto extra: ${surf_minute_overage}")
print(f"- Costo por SMS extra: ${surf_sms_overage}")
print(f"- Costo por GB extra: ${surf_gb_overage}")

print("\nTARIFA ULTIMATE:")
print(f"- Pago mensual: ${ultimate_monthly_fee}")
print(f"- Minutos incluidos: {ultimate_minutes_included}")
print(f"- SMS incluidos: {ultimate_sms_included}")
print(f"- GB incluidos: {ultimate_gb_included}")
print(f"- Costo por minuto extra: ${ultimate_minute_overage}")
print(f"- Costo por SMS extra: ${ultimate_sms_overage}")
print(f"- Costo por GB extra: ${ultimate_gb_overage}")

# ... y así sucesivamente

*** CONDICIONES DE LAS TARIFAS ***

TARIFA SURF:
- Pago mensual: $20
- Minutos incluidos: 500
- SMS incluidos: 50
- GB incluidos: 15
- Costo por minuto extra: $0.03
- Costo por SMS extra: $0.03
- Costo por GB extra: $10

TARIFA ULTIMATE:
- Pago mensual: $70
- Minutos incluidos: 3000
- SMS incluidos: 1000
- GB incluidos: 30
- Costo por minuto extra: $0.01
- Costo por SMS extra: $0.01
- Costo por GB extra: $7

## Agregar datos por usuario

Vamos a desglozar la información contenida en el DataFrame calls_df, a nivel de llamadas realizadas, minutos, mensajes y megas consumidas. Para esto, nos valdremos de los métodos groupby(), reset_index(), columns(), entre otros

In [41]:
# Calcula el número de llamadas hechas por cada usuario al mes. Guarda el resultado
"""
Código que contabiliza la cantidad de llamadas realizadas por cada usuario por mes

"""
# Creamos una columna que incluya el mes
calls_df['month'] = calls_df['call_date'].dt.month
# Agrupamos por mes y por llamadas realizadas
calls_per_user = calls_df.groupby(["user_id", "month"])["id"].count().reset_index()
# asignamos nombre a las columnas
calls_per_user.columns = ["user_id", "month", "calls_count"]
print(calls_per_user) # imprimimos resultado

      user_id  month  calls_count
0        1000     12           16
1        1001      8           27
2        1001      9           49
3        1001     10           65
4        1001     11           64
...       ...    ...          ...
2253     1498     12           39
2254     1499      9           41
2255     1499     10           53
2256     1499     11           45
2257     1499     12           65

[2258 rows x 3 columns]

In [42]:
# Calcula la cantidad de minutos usados por cada usuario al mes. Guarda el resultado.
minutes_per_user = calls_df.groupby(["user_id","month"])["duration"].sum().reset_index()
print(minutes_per_user)

      user_id  month  duration
0        1000     12    116.83
1        1001      8    171.14
2        1001      9    297.69
3        1001     10    374.11
4        1001     11    404.59
...       ...    ...       ...
2253     1498     12    324.77
2254     1499      9    330.37
2255     1499     10    363.28
2256     1499     11    288.56
2257     1499     12    468.10

[2258 rows x 3 columns]

In [43]:
# Calcula el número de mensajes enviados por cada usuario al mes. Guarda el resultado.
"""
Código que contabiliza cantidad de mensajes enviados por usuario, a partir del merge de 2 DataFrames
Output = messages_per_user
Type: DataFrame
"""
# Creamos columna con el mes de cada mensaje
messages_df["month"] = messages_df["message_date"].dt.month
# Hacemos un merge con el df messages_df & users_df
users_and_messages_df = messages_df.merge(users_df, on="user_id", how="inner")
# Agrupamos por user_id y contamos cantidad de mensajes enviados por cada uno
messages_per_user = users_and_messages_df.groupby(["user_id","month"])["first_name"].size().reset_index() # reseteamos índices para crear nuevp DataFrame
# Asignamos nombres a columnas
messages_per_user.columns = ["user_id", "month","messages_sent"]
# imprimimos muestra de 5 registros de la agrupación anterior
print(messages_per_user.head())
# Imprimimos info del nuevo DataFrame para corroborar info contenida
print(messages_per_user.info())

   user_id  month  messages_sent
0     1000     12             11
1     1001      8             30
2     1001      9             44
3     1001     10             53
4     1001     11             36
<class 'pandas.DataFrame'>
RangeIndex: 1806 entries, 0 to 1805
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   user_id        1806 non-null   int64
 1   month          1806 non-null   int32
 2   messages_sent  1806 non-null   int64
dtypes: int32(1), int64(2)
memory usage: 35.4 KB
None

In [44]:
# Calcula el volumen del tráfico de Internet usado por cada usuario al mes. Guarda el resultado.
# Creamos columna con el número del mes
internet_df["month"] = internet_df["session_date"].dt.month
# Agrupamos por user_id y por mes
mb_used_by_user = internet_df.groupby(["user_id","month"])["mb_used"].sum().reset_index() # Creamos el df agrupado por usuario que muestra mb utilizados
# Damos nombre a las columnas
mb_used_by_user.columns = ["user_id", "month", "mb_used_per_user"] # Asignamos nombres a las columnas
print(mb_used_by_user)

      user_id  month  mb_used_per_user
0        1000     12           1901.47
1        1001      8           6919.15
2        1001      9          13314.82
3        1001     10          22330.49
4        1001     11          18504.30
...       ...    ...               ...
2272     1498     12          23137.69
2273     1499      9          12984.76
2274     1499     10          19492.43
2275     1499     11          16813.83
2276     1499     12          22059.21

[2277 rows x 3 columns]

In [ ]:
# Fusiona los datos de llamadas, minutos, mensajes e Internet con base en user_id y month
# Agrupamos llamadas por user_id y mes, contamos columna id y sumamos la duración
calls_monthly = calls_df.groupby(["user_id", "month"]).agg({"id": "count","duration": "sum"}).reset_index()
calls_monthly.columns = ["user_id", "month", 'calls_count', 'minutes_used']
# agrupamos el df de mensajes por user_id y por mes, contamos por ID y reeteamos índuces
messages_monthly = messages_df.groupby(["user_id", "month"]).agg({"id": "count"}).reset_index()
# Asignamos nombre a las columnas del nuevo DataFrame
messages_monthly.columns = ["user_id", "month", "messages_count"]
# Hacemos merge entre los 2 dfs
calls_and_messages_df = calls_monthly.merge(
    messages_monthly,
    on=["user_id", "month"], 
    how="outer",
    suffixes=["_calls", "_messages"])
# Ahora unimos con el df de internet, pero primero agrupamos por user_id ese df
internet_monthly = internet_df.groupby(["user_id","month"]).agg({"id": "count", "mb_used": "sum"}).reset_index()
# Nombramos las columnas del df creado para internet
internet_monthly.columns = ["user_id", "month", "sessions_count", "mb_used"]
# Hacemos el último merge para juntar las 3 bases de datos
final_merge = calls_and_messages_df.merge(internet_monthly, on=["user_id", "month"], how="outer")
print(final_merge.head()) # imprimimos para corroborar datos
print(final_merge.info()) # imprimimos para corroborar el df completo

user_id           2293
month             2293
calls_count       2293
minutes_used      2293
messages_count    2293
sessions_count    2293
mb_used           2293
dtype: int64
16051
    user_id  month  calls_count  minutes_used  messages_count  sessions_count  \
0      1000     12         16.0        116.83            11.0             5.0
1      1001      8         27.0        171.14            30.0            25.0
2      1001      9         49.0        297.69            44.0            53.0
3      1001     10         65.0        374.11            53.0            56.0
4      1001     11         64.0        404.59            36.0            51.0
5      1001     12         56.0        392.93            44.0            60.0
6      1002     10         11.0         54.13            15.0            21.0
7      1002     11         55.0        359.76            32.0            52.0
8      1002     12         47.0        363.24            41.0            51.0
9      1003     12        149.0       1041.00            50.0            52.0
10     1004      5         21.0        181.58             7.0            17.0
11     1004      6         44.0        261.32            18.0            73.0
12     1004      7         49.0        358.45            26.0            69.0
13     1004      8         49.0        334.86            25.0            72.0
14     1004      9         42.0        284.60            21.0            56.0
15     1004     10         61.0        341.63            24.0            51.0
16     1004     11         54.0        452.98            25.0            69.0
17     1004     12         50.0        403.53            31.0            53.0
18     1005     12         59.0        470.22            11.0            60.0
19     1006     11          2.0          9.32            15.0             7.0

     mb_used
0    1901.47
1    6919.15
2   13314.82
3   22330.49
4   18504.30
5   19369.18
6    6552.01
7   19345.08
8   14396.24
9   27044.14
10   6547.21
11  20672.82
12  24516.62
13  27981.74
14  18852.72
15  14541.63
16  21850.78
17  21389.29
18  17140.17
19   2068.37

In [57]:
print(final_merge.columns.tolist())

['user_id', 'month', 'calls_count', 'minutes_used', 'messages_count', 'sessions_count', 'mb_used']

In [ ]:
# Añade la información de la tarifa

[Calcula los ingresos mensuales por usuario (resta el límite del paquete gratuito del número total de llamadas, mensajes de texto y datos; multiplica el resultado por el valor del plan de llamadas; añade la tarifa mensual en función del plan de llamadas). Nota: Dadas las condiciones del plan, ¡esto podría no ser tan trivial como un par de líneas! Así que no pasa nada si dedicas algo de tiempo a ello.]

In [35]:
# Calcula el ingreso mensual para cada usuario

## Estudia el comportamiento de usuario

[Calcula algunas estadísticas descriptivas para los datos agregados y fusionados que nos sean útiles y que muestren un panorama general captado por los datos. Dibuja gráficos útiles para facilitar la comprensión. Dado que la tarea principal es comparar las tarifas y decidir cuál es más rentable, las estadísticas y gráficas deben calcularse por tarifa.]

[En los comentarios hallarás pistas relevantes para las llamadas, pero no las hay para los mensajes e Internet. Sin embargo, el principio del estudio estadístico que se aplica para ellos es el mismo que para las llamadas.]

### Llamadas

In [36]:
# Compara la duración promedio de llamadas por cada plan y por cada mes. Traza un gráfico de barras para visualizarla.

In [37]:
# Compara el número de minutos mensuales que necesitan los usuarios de cada plan. Traza un histograma.

[Calcula la media y la variable de la duración de las llamadas para averiguar si los usuarios de los distintos planes se comportan de forma diferente al realizar sus llamadas.]

In [38]:
# Calcula la media y la varianza de la duración mensual de llamadas.

In [39]:
# Traza un diagrama de caja para visualizar la distribución de la duración mensual de llamadas

[Elabora las conclusiones sobre el comportamiento de los usuarios con respecto a las llamadas. ¿Su comportamiento varía en función del plan?]

### Mensajes

In [40]:
# Comprara el número de mensajes que tienden a enviar cada mes los usuarios de cada plan

In [41]:
# Compara la cantidad de tráfico de Internet consumido por usuarios por plan

[Elabora las conclusiones sobre el comportamiento de los usuarios con respecto a los mensajes. ¿Su comportamiento varía en función del plan?]

### Internet

[Elabora las conclusiones sobre cómo los usuarios tienden a consumir el tráfico de Internet. ¿Su comportamiento varía en función del plan?]

## Ingreso

[Del mismo modo que has estudiado el comportamiento de los usuarios, describe estadísticamente los ingresos de los planes.]

[Elabora las conclusiones sobre cómo difiere el ingreso entre los planes.]

## Prueba las hipótesis estadísticas

[Prueba la hipótesis de que son diferentes los ingresos promedio procedentes de los usuarios de los planes de llamada Ultimate y Surf.]

[Elabora las hipótesis nula y alternativa, escoge la prueba estadística, determina el valor alfa.]

In [42]:
# Prueba las hipótesis

[Prueba la hipótesis de que el ingreso promedio de los usuarios del área NY-NJ es diferente al de los usuarios de otras regiones.]

[Elabora las hipótesis nula y alternativa, escoge la prueba estadística, determina el valor alfa.]

In [43]:
# Prueba las hipótesis

## Conclusión general

[En esta sección final, enumera tus conclusiones importantes. Asegúrate de que estas abarquen todas las decisiones (suposiciones) importantes que adoptaste y que determinaron la forma elegida para procesar y analizar los datos.]